### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Fumesover** [kynzie/docker-python-algo-sup#1]
Alors du coup je reprends ca, pour ne pas me faire lincher, jvais tenter d'etre un chouilla plus precis.
J'ai les tools necessaires suivants dans les versions suivantes : 
* docker : `Docker version 18.02.0-ce, build fc4de447b5`
* docker-compose : `docker-compose version 1.18.0`
* python : `Python 3.6.4`
* kernel : `4.15.2-2-ARCH`

Dans l'ordre, 
1. `docker build -t jupyter:algo .` passe sans probleme.
1. `docker run -it --rm -p 8888:8888 -v /home/fumesover/Epita/Algo/docker-python-algo-sup:/home/jovyan/work jupyter:algo` fonctionne tout aussi bien, le notebook est accessible et est fonctionnel.
1. `WORK_DIR=$HOME/notebook-python docker-compose run --rm --service-ports -d algo-sup` me retourne `dockerpythonalgosup_algo-sup_run_4`, et quand je lis les logs du containeur avec `docker logs dockerpythonalgosup_algo-sup_run_4`, j'obtiens l'erreur suivante : 

```
Container must be run as root to set $NB_GID
Executing the command: jupyter notebook
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1366, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 1100, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'
```

**Comment by kynzie** [comment]
Documentation fixed.
